
    // Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;
import sun.awt.windows.WBufferStrategy;


    public class PierwszeTesty {
        private WebDriver driver;
        //@befor tag mówiacy nam o tym ze wszytko w metodzie setup musi byc wykonane przed uruchomieniem testu
        @Before
        public void setUp() {
            WebDriverManager.firefoxdriver().setup();
            driver = new FirefoxDriver();

        }
        //@after uruchamia sie zawsze po zakończeniu testu
        @After
        public void tearDown() {
            // quit - zamknij przegladarke
            driver.quit();
        }

        //jest to tag, którym mówi nam, ze metoda testCase1 jest metoda testowa
        @Ignore
        @Test
        public void testCase1() {
            //metoda get otwiera nam adres internetowy
            driver.get("https://www.google.com/");
            // metoda sendKeys wpisuje tekst do pola
            driver.findElement(By.name("q")).sendKeys("test ");

        }
        @Ignore
        @Test
        public void logowanieDoFacebooka() throws InterruptedException {
            // krok 1 - otwiramy strone
            driver.get("http://facebook.com");
            //krok 2 - w okienku adres wpisujemy maila
            // znajdz okienko 2.wpisz text
            WebElement email = driver.findElement(By.id("email"));
            email.sendKeys("test");
            Thread.sleep(5000);
            //krok 3 - w okienku hasło wpisujemy hasło
            // 1 znajdujemy element 2 wpisujemy tekt
            WebElement password = driver.findElement(By.id("pass"));
            password.sendKeys("test");
            Thread.sleep(5000);
            //krok 4 - kliknij zaloguj się
            // 1 znajdz element 2 kliknij na niego
            WebElement zaloguj = driver.findElement(By.id("u_0_c"));
            zaloguj.click();
            Thread.sleep(5000);

        }
        @Ignore
        @Test
        public void logowanie(){
            //krok 1 otwieramy strone
            driver.get("http://zadaniadlatestera.pl/textBox.html");
            // 2 wpisujemy login
            WebElement login = driver.findElement(By.id("login"));
            // 3 wpisujemy haslo
            login.sendKeys("test login");

            WebElement password =driver.findElement(By.id("password"));
            password.sendKeys("tekst hasla");
            // 4 klikamy przycisk przeslij
            WebElement przeslij = driver.findElement(By.id("sendLogin"));
            przeslij.click();


        }
        @Ignore
        @Test
        public void rejestracja(){
            //otworz stronę
            driver.get("http://zadaniadlatestera.pl/textBox.html");
            //wypełnij imie
            WebElement imie=driver.findElement(By.id("name"));
            imie.sendKeys("Kaska");
            //wypełnij nazwisko
            WebElement nazwisko=driver.findElement(By.id("surname"));
            nazwisko.sendKeys("Nowak");
            //wypełnij pesel
            WebElement pesel=driver.findElement(By.id("personalId"));
            pesel.sendKeys("123443554");
            //wypełnij numer telefonu
            WebElement numerTelefonu=driver.findElement(By.name("phoneNumber"));
            numerTelefonu.sendKeys("123382");
            //kliknij wyslij zapytanie
            WebElement wyslijzapytanie=driver.findElement(By.name("send"));
            wyslijzapytanie.click();

        }
        @Ignore
        @Test
        public void ankieta(){
            //otwieramy strone
            driver.get("http://zadaniadlatestera.pl/radioButton.html");
            //wybierz płeć
            WebElement kobieta = driver.findElement(By.id("woman"));
            kobieta.click();
            //wybierz wiek
            WebElement wiek=driver.findElement(By.id("age2"));
            wiek.click();
            //wybierz wyksztąłcenie
            WebElement wyksztalcenie=driver.findElement(By.id("level2"));
            wyksztalcenie.click();
            //wybioerz miejsce zamieszkania
            WebElement zamieszkanie=driver.findElement(By.id("city"));
            zamieszkanie.click();
            //czy lubisz sowje zapytanie
            WebElement praca=driver.findElement(By.id("no"));
            praca.click();
            //wyslij
            WebElement wyslij=driver.findElement(By.name("send"));
            wyslij.click();
        }


        @Ignore
        @Test
        public void chekboxy(){
            driver.get("http://zadaniadlatestera.pl/checkbox.html");
            WebElement czytanie=driver.findElement(By.id("reading"));
            czytanie.click();
            WebElement fotografia=driver.findElement(By.name("photo"));
            fotografia.click();
            WebElement gry=driver.findElement(By.id("games"));
            gry.click();
        }
        @Ignore
        @Test
        public void select() throws InterruptedException {
            driver.get("http://zadaniadlatestera.pl/select.html");
            Select gatunek = new Select(driver.findElement(By.name("sort")));
            //wybierz z listy hymn
            gatunek.selectByValue("Hymn");
            Thread.sleep(3000);
            Select wiek = new Select(driver.findElement(By.name("age")));
            wiek.selectByIndex(1);
            Thread.sleep(3000);

            Select regal = new Select(driver.findElement(By.name("place")));
            regal.selectByVisibleText("VI");
            regal.selectByIndex(0);
            regal.selectByValue("vii");
            regal.deselectAll();

            WebElement numer =driver.findElement(By.id("index"));
            numer.sendKeys("cos");
            Select osobaOd = new Select(driver.findElement(By.name("personName")));
            osobaOd.selectByValue("osoba4");
            WebElement wyslij=driver.findElement(By.id("send"));
            wyslij.click();

        }//wpisac numer porzadkowy
        //zaznaczyc osobe odpowiedzialna  pawel mikus
        // kliknij wyslij zapytanie

        @Test
        public void alert(){
            driver.get("http://zadaniadlatestera.pl/alert1.html");
            WebElement decyzja = driver.findElement(By.id("dec"));
            decyzja.click();
            Alert alert = driver.switchTo().alert();
            //klikamy ok
            //alert.accept();
            //klikamy anuluj
            alert.dismiss();
        }

        @Test
        public void alert2(){
            driver.get("http://zadaniadlatestera.pl/alert2.html");
            //wpisz indeks do text Boxa
            WebElement wpisz=driver.findElement(By.id("index"));
            wpisz.sendKeys("cokolwiek");
            WebElement skasuj=driver.findElement(By.id("delete"));
            skasuj.click();
            Alert alert=driver.switchTo().alert();
            alert.accept();
            //kliknij skasuj
            //zakceptuj slert

        }
    }

